"""add ai_pricing_recommendations table

Revision ID: 0bac8c8d436f
Revises: c880c18675aa
Create Date: 2026-08-26 11:18:02.710597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0bac8c8d436f'
down_revision: Union[str, None] = 'c880c18675aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_pricing_recommendations',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('store_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('product_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('recommended_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('recommendation_reason', sa.Text(), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'APPLIED', 'EXPIRED', name='recommendationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_by_agent', sa.String(length=100), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_pricing_recommendations_organization_id'), 'ai_pricing_recommendations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_pricing_recommendations_product_id'), 'ai_pricing_recommendations', ['product_id'], unique=False)
    op.create_index(op.f('ix_ai_pricing_recommendations_status'), 'ai_pricing_recommendations', ['status'], unique=False)
    op.create_index(op.f('ix_ai_pricing_recommendations_store_id'), 'ai_pricing_recommendations', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_pricing_recommendations_store_id'), table_name='ai_pricing_recommendations')
    op.drop_index(op.f('ix_ai_pricing_recommendations_status'), table_name='ai_pricing_recommendations')
    op.drop_index(op.f('ix_ai_pricing_recommendations_product_id'), table_name='ai_pricing_recommendations')
    op.drop_index(op.f('ix_ai_pricing_recommendations_organization_id'), table_name='ai_pricing_recommendations')
    op.drop_table('ai_pricing_recommendations')
    # ### end Alembic commands ###
