"""add inventory and inventory_adjustments tables

Revision ID: 29e0d36e7acf
Revises: 83921e864ba5
Create Date: 2026-08-25 12:41:23.497233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '29e0d36e7acf'
down_revision: Union[str, None] = '83921e864ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('store_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('product_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('safety_stock', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('last_stock_update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'store_id', 'product_id', name='uq_inventory_org_store_product')
    )
    op.create_index(op.f('ix_inventory_organization_id'), 'inventory', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_store_id'), 'inventory', ['store_id'], unique=False)
    op.create_table('inventory_adjustments',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('inventory_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('adjustment_type', sa.Enum('INCREASE', 'DECREASE', 'CORRECTION', name='adjustmenttype', native_enum=False, length=20), nullable=False),
    sa.Column('adjustment_quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('quantity_before', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('quantity_after', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_adjustments_inventory_id'), 'inventory_adjustments', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_organization_id'), 'inventory_adjustments', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Dropping a table implicitly drops its indexes and FK constraints in
    # MySQL/InnoDB; an explicit drop_index first fails with "needed in a
    # foreign key constraint". inventory_adjustments before inventory: it
    # references inventory.id.
    op.drop_table('inventory_adjustments')
    op.drop_table('inventory')
