"""add output_channels and output_jobs tables

Revision ID: 41913834c81c
Revises: dd0f7fae3f7d
Create Date: 2026-08-25 16:01:02.207809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '41913834c81c'
down_revision: Union[str, None] = 'dd0f7fae3f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('output_channels',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('store_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('output_type', sa.Enum('ESL_SIMULATOR', 'QR_CODE', 'PDF_LABEL', 'WEB_DISPLAY', name='outputtype', native_enum=False, length=20), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='outputchannelstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_output_channels_organization_id'), 'output_channels', ['organization_id'], unique=False)
    op.create_index(op.f('ix_output_channels_store_id'), 'output_channels', ['store_id'], unique=False)
    op.create_table('output_jobs',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('output_channel_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('product_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('store_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='outputjobstatus', native_enum=False, length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['output_channel_id'], ['output_channels.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_output_jobs_organization_id'), 'output_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_output_jobs_output_channel_id'), 'output_jobs', ['output_channel_id'], unique=False)
    op.create_index(op.f('ix_output_jobs_product_id'), 'output_jobs', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # MySQL/InnoDB refuses to drop an index still backing a foreign key
    # constraint, so tables (and their indexes) are dropped outright in FK
    # dependency order rather than via the autogenerated drop_index calls.
    op.drop_table('output_jobs')
    op.drop_table('output_channels')
