"""add output_routing_rules table and output_jobs idempotency columns

Revision ID: 4808a5de4384
Revises: df4ef27ba8d4
Create Date: 2026-08-26 12:36:33.900279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '4808a5de4384'
down_revision: Union[str, None] = 'df4ef27ba8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('output_routing_rules',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('conditions_json', sa.JSON(), nullable=True),
    sa.Column('target_outputs_json', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='routingrulestatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_output_routing_rules_organization_id'), 'output_routing_rules', ['organization_id'], unique=False)
    op.alter_column('output_channels', 'output_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('ESL_SIMULATOR', 'QR_CODE', 'PDF_LABEL', 'WEB_DISPLAY', 'POS_INTEGRATION', 'ECOMMERCE_INTEGRATION', 'DIGITAL_SIGNAGE', name='outputtype', native_enum=False, length=30),
               existing_nullable=False)
    op.add_column('output_jobs', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.add_column('output_jobs', sa.Column('routing_rule_id', sa.Uuid(native_uuid=False), nullable=True))
    op.add_column('output_jobs', sa.Column('source_price_id', sa.Uuid(native_uuid=False), nullable=True))
    op.create_index(op.f('ix_output_jobs_idempotency_key'), 'output_jobs', ['idempotency_key'], unique=True)
    op.create_foreign_key(
        'fk_output_jobs_source_price_id', 'output_jobs', 'prices', ['source_price_id'], ['id']
    )
    op.create_foreign_key(
        'fk_output_jobs_routing_rule_id', 'output_jobs', 'output_routing_rules', ['routing_rule_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_output_jobs_routing_rule_id', 'output_jobs', type_='foreignkey')
    op.drop_constraint('fk_output_jobs_source_price_id', 'output_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_output_jobs_idempotency_key'), table_name='output_jobs')
    op.drop_column('output_jobs', 'source_price_id')
    op.drop_column('output_jobs', 'routing_rule_id')
    op.drop_column('output_jobs', 'idempotency_key')
    op.alter_column('output_channels', 'output_type',
               existing_type=sa.Enum('ESL_SIMULATOR', 'QR_CODE', 'PDF_LABEL', 'WEB_DISPLAY', 'POS_INTEGRATION', 'ECOMMERCE_INTEGRATION', 'DIGITAL_SIGNAGE', name='outputtype', native_enum=False, length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_output_routing_rules_organization_id'), table_name='output_routing_rules')
    op.drop_table('output_routing_rules')
    # ### end Alembic commands ###
