"""add pushed_records to integration_sync_jobs

Revision ID: 543415371808
Revises: d1a85ca1e66f
Create Date: 2026-08-25 19:21:24.027974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '543415371808'
down_revision: Union[str, None] = 'd1a85ca1e66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_sync_jobs', sa.Column('pushed_records', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_sync_jobs', 'pushed_records')
    # ### end Alembic commands ###
