"""add esl_integrations table and devices esl_integration_id

Revision ID: 63501503a51e
Revises: 9c4e2a6f8d1b
Create Date: 2026-08-25 17:38:03.681050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '63501503a51e'
down_revision: Union[str, None] = '9c4e2a6f8d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esl_integrations',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('vendor_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('integration_type', sa.Enum('MOCK', 'MQTT', 'API', name='eslintegrationtype', native_enum=False, length=20), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('configuration_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'ERROR', 'INACTIVE', name='eslintegrationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['device_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esl_integrations_organization_id'), 'esl_integrations', ['organization_id'], unique=False)
    op.add_column('devices', sa.Column('esl_integration_id', sa.Uuid(native_uuid=False), nullable=True))
    op.create_foreign_key(
        'fk_devices_esl_integration_id', 'devices', 'esl_integrations', ['esl_integration_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # MySQL requires an explicit constraint name to drop a foreign key
    # (autogenerate's placeholder `None` doesn't work), and refuses to drop
    # a column still backing one — the FK is dropped before the column.
    op.drop_constraint('fk_devices_esl_integration_id', 'devices', type_='foreignkey')
    op.drop_column('devices', 'esl_integration_id')
    op.drop_table('esl_integrations')
