"""add device vendors models devices assignments and sync logs

Revision ID: 84c22ab0df4a
Revises: 7f2a4c9d1e3b
Create Date: 2026-08-25 16:34:51.747024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '84c22ab0df4a'
down_revision: Union[str, None] = '7f2a4c9d1e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_vendors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='devicevendorstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('device_models',
    sa.Column('vendor_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_code', sa.String(length=100), nullable=False),
    sa.Column('screen_size', sa.String(length=50), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('color_capabilities', sa.JSON(), nullable=True),
    sa.Column('battery_type', sa.String(length=50), nullable=True),
    sa.Column('communication_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='devicemodelstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['device_vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_models_vendor_id'), 'device_models', ['vendor_id'], unique=False)
    op.create_table('devices',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('store_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('vendor_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('device_model_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('device_identifier', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'OFFLINE', 'MAINTENANCE', name='devicestatus', native_enum=False, length=20), nullable=False),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('signal_strength', sa.Integer(), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_model_id'], ['device_models.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['device_vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'device_identifier', name='uq_devices_organization_id_device_identifier')
    )
    op.create_index(op.f('ix_devices_organization_id'), 'devices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_devices_store_id'), 'devices', ['store_id'], unique=False)
    op.create_table('device_assignments',
    sa.Column('device_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('product_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('store_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='deviceassignmentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_assignments_device_id'), 'device_assignments', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_assignments_product_id'), 'device_assignments', ['product_id'], unique=False)
    op.create_table('device_sync_logs',
    sa.Column('device_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('product_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('output_job_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='devicesyncstatus', native_enum=False, length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['output_job_id'], ['output_jobs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_sync_logs_device_id'), 'device_sync_logs', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # MySQL/InnoDB refuses to drop an index still backing a foreign key
    # constraint, so tables (and their indexes) are dropped outright in FK
    # dependency order rather than via the autogenerated drop_index calls.
    op.drop_table('device_sync_logs')
    op.drop_table('device_assignments')
    op.drop_table('devices')
    op.drop_table('device_models')
    op.drop_table('device_vendors')
