"""add stores table

Revision ID: 9305e1560b7f
Revises: eaa27d8a5e16
Create Date: 2026-08-25 11:51:44.744917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9305e1560b7f'
down_revision: Union[str, None] = 'eaa27d8a5e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('store_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('store_type', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=30), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'CLOSED', name='storestatus', native_enum=False, length=20), nullable=False),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'store_code', name='uq_stores_organization_id_store_code')
    )
    op.create_index(op.f('ix_stores_organization_id'), 'stores', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Dropping the table implicitly drops its indexes and FK constraints in
    # MySQL/InnoDB; an explicit drop_index first fails with "needed in a
    # foreign key constraint" since it backs the organization_id FK.
    op.drop_table('stores')
