"""add import_jobs and import_row_errors tables

Revision ID: a28c3123de63
Revises: e849cf59dc1f
Create Date: 2026-08-25 13:19:24.625698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a28c3123de63'
down_revision: Union[str, None] = 'e849cf59dc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('store_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('CSV', 'XLSX', name='importfiletype', native_enum=False, length=10), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('entity_type', sa.Enum('PRODUCTS', 'INVENTORY', name='importentitytype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', name='importstatus', native_enum=False, length=30), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_columns', sa.JSON(), nullable=True),
    sa.Column('column_mapping', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_organization_id'), 'import_jobs', ['organization_id'], unique=False)
    op.create_table('import_row_errors',
    sa.Column('import_job_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_row_errors_import_job_id'), 'import_row_errors', ['import_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Dropping a table implicitly drops its indexes and FK constraints in
    # MySQL/InnoDB; an explicit drop_index first fails with "needed in a
    # foreign key constraint". import_row_errors before import_jobs: it
    # references import_jobs.id.
    op.drop_table('import_row_errors')
    op.drop_table('import_jobs')
