"""add categories and products tables

Revision ID: abcbb36b2bb2
Revises: 9305e1560b7f
Create Date: 2026-08-25 12:22:18.240100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'abcbb36b2bb2'
down_revision: Union[str, None] = '9305e1560b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('parent_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='categorystatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_organization_id'), 'categories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_table('products',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('category_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('sku', sa.String(length=150), nullable=False),
    sa.Column('barcode', sa.String(length=150), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DISCONTINUED', name='productstatus', native_enum=False, length=20), nullable=False),
    sa.Column('product_image_url', sa.String(length=500), nullable=True),
    sa.Column('weight', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('weight_unit', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'sku', name='uq_products_organization_id_sku')
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Dropping a table implicitly drops its indexes and FK constraints in
    # MySQL/InnoDB; an explicit drop_index first fails with "needed in a
    # foreign key constraint" since these back the organization_id/
    # category_id/parent_id FKs. products before categories: products
    # references categories.
    op.drop_table('products')
    op.drop_table('categories')
