"""add integrations integration_sync_jobs and integration_mappings

Revision ID: d1a85ca1e66f
Revises: 7b3d9f2e5a1c
Create Date: 2026-08-25 19:11:09.553040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd1a85ca1e66f'
down_revision: Union[str, None] = '7b3d9f2e5a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('integration_category', sa.Enum('ERP', 'POS', 'ECOMMERCE', 'MARKETPLACE', 'CUSTOM', name='integrationcategory', native_enum=False, length=20), nullable=False),
    sa.Column('provider', sa.Enum('CSV', 'REST_API', 'WEBHOOK', 'SAP', 'ORACLE', name='integrationprovider', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'ERROR', 'INACTIVE', name='integrationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('configuration_encrypted', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_organization_id'), 'integrations', ['organization_id'], unique=False)
    op.create_table('integration_mappings',
    sa.Column('integration_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('entity_type', sa.Enum('PRODUCT', 'PRICE', 'INVENTORY', 'PROMOTION', 'STORE', name='canonicalentitytype', native_enum=False, length=20), nullable=False),
    sa.Column('source_field', sa.String(length=255), nullable=False),
    sa.Column('canonical_field', sa.String(length=255), nullable=False),
    sa.Column('transformation_rule', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_mappings_integration_id'), 'integration_mappings', ['integration_id'], unique=False)
    op.create_table('integration_sync_jobs',
    sa.Column('integration_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('job_type', sa.Enum('FULL_SYNC', 'INCREMENTAL_SYNC', name='integrationsyncjobtype', native_enum=False, length=20), nullable=False),
    sa.Column('entity_type', sa.Enum('PRODUCT', 'PRICE', 'INVENTORY', 'PROMOTION', 'STORE', name='canonicalentitytype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', name='integrationsyncjobstatus', native_enum=False, length=25), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_sync_jobs_integration_id'), 'integration_sync_jobs', ['integration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # MySQL/InnoDB refuses to drop an index still backing a foreign key
    # constraint, so tables (and their indexes) are dropped outright in FK
    # dependency order rather than via the autogenerated drop_index calls.
    op.drop_table('integration_sync_jobs')
    op.drop_table('integration_mappings')
    op.drop_table('integrations')
