"""add prices, price_history, pricing_rules tables

Revision ID: dd0f7fae3f7d
Revises: 3dcfb4ae03c1
Create Date: 2026-08-25 13:58:04.550451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd0f7fae3f7d'
down_revision: Union[str, None] = '3dcfb4ae03c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_rules',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.Enum('FIXED_PRICE', 'PERCENTAGE_DISCOUNT', 'FIXED_DISCOUNT', 'MARGIN_BASED', 'COST_PLUS', 'INVENTORY_BASED', 'TIME_BASED', 'STORE_SPECIFIC', 'PROMOTION', 'CLEARANCE', name='ruletype', native_enum=False, length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('conditions_json', sa.JSON(), nullable=True),
    sa.Column('actions_json', sa.JSON(), nullable=False),
    sa.Column('constraints_json', sa.JSON(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'EXPIRED', name='rulestatus', native_enum=False, length=20), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rules_organization_id'), 'pricing_rules', ['organization_id'], unique=False)
    op.create_table('price_history',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('store_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('product_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('new_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_organization_id'), 'price_history', ['organization_id'], unique=False)
    op.create_index(op.f('ix_price_history_product_id'), 'price_history', ['product_id'], unique=False)
    op.create_table('prices',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('store_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('product_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('price_type', sa.Enum('REGULAR', 'PROMOTIONAL', 'CLEARANCE', 'CONTRACT', name='pricetype', native_enum=False, length=20), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SCHEDULED', 'EXPIRED', name='pricestatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_organization_id'), 'prices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_prices_product_id'), 'prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_prices_store_id'), 'prices', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Dropping a table implicitly drops its indexes and FK constraints in
    # MySQL/InnoDB; an explicit drop_index first fails with "needed in a
    # foreign key constraint".
    op.drop_table('prices')
    op.drop_table('price_history')
    op.drop_table('pricing_rules')
