"""add competitors, competitor_products, competitor_prices tables

Revision ID: df4ef27ba8d4
Revises: e12f8cb05955
Create Date: 2026-08-26 12:05:56.214298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'df4ef27ba8d4'
down_revision: Union[str, None] = 'e12f8cb05955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='competitorstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_organization_id'), 'competitors', ['organization_id'], unique=False)
    op.create_table('competitor_products',
    sa.Column('competitor_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('product_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('external_product_url', sa.String(length=1000), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='competitorproductstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_products_competitor_id'), 'competitor_products', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_competitor_products_product_id'), 'competitor_products', ['product_id'], unique=False)
    op.create_table('competitor_prices',
    sa.Column('competitor_product_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['competitor_product_id'], ['competitor_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_prices_competitor_product_id'), 'competitor_prices', ['competitor_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitor_prices_competitor_product_id'), table_name='competitor_prices')
    op.drop_table('competitor_prices')
    op.drop_index(op.f('ix_competitor_products_product_id'), table_name='competitor_products')
    op.drop_index(op.f('ix_competitor_products_competitor_id'), table_name='competitor_products')
    op.drop_table('competitor_products')
    op.drop_index(op.f('ix_competitors_organization_id'), table_name='competitors')
    op.drop_table('competitors')
    # ### end Alembic commands ###
