"""add ai_agents, ai_agent_runs, ai_policies tables

Revision ID: e12f8cb05955
Revises: a1f3c9d2b6e4
Create Date: 2026-08-26 11:47:24.105493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e12f8cb05955'
down_revision: Union[str, None] = 'a1f3c9d2b6e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agents',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('agent_type', sa.Enum('PRICING_OPTIMIZATION', 'INVENTORY_HEALTH', 'PROMOTION', 'DEVICE_OPERATIONS', 'INTEGRATION_MONITORING', name='agenttype', native_enum=False, length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='agentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_agents_agent_type'), 'ai_agents', ['agent_type'], unique=False)
    op.create_index(op.f('ix_ai_agents_organization_id'), 'ai_agents', ['organization_id'], unique=False)
    op.create_table('ai_policies',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('agent_type', sa.Enum('PRICING_OPTIMIZATION', 'INVENTORY_HEALTH', 'PROMOTION', 'DEVICE_OPERATIONS', 'INTEGRATION_MONITORING', name='agenttype', native_enum=False, length=30), nullable=False),
    sa.Column('mode', sa.Enum('RECOMMENDATION_ONLY', 'APPROVAL_REQUIRED', 'AUTO_EXECUTE_WITHIN_LIMITS', name='policymode', native_enum=False, length=30), nullable=False),
    sa.Column('min_confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('max_price_change_percent', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('min_margin_percent', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('auto_execute', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'agent_type', name='uq_ai_policies_organization_id_agent_type')
    )
    op.create_index(op.f('ix_ai_policies_agent_type'), 'ai_policies', ['agent_type'], unique=False)
    op.create_index(op.f('ix_ai_policies_organization_id'), 'ai_policies', ['organization_id'], unique=False)
    op.create_table('ai_agent_runs',
    sa.Column('agent_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('trigger_type', sa.Enum('MANUAL', 'SCHEDULED', name='triggertype', native_enum=False, length=20), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='agentrunstatus', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['ai_agents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_agent_runs_agent_id'), 'ai_agent_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_ai_agent_runs_organization_id'), 'ai_agent_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_agent_runs_status'), 'ai_agent_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_agent_runs_status'), table_name='ai_agent_runs')
    op.drop_index(op.f('ix_ai_agent_runs_organization_id'), table_name='ai_agent_runs')
    op.drop_index(op.f('ix_ai_agent_runs_agent_id'), table_name='ai_agent_runs')
    op.drop_table('ai_agent_runs')
    op.drop_index(op.f('ix_ai_policies_organization_id'), table_name='ai_policies')
    op.drop_index(op.f('ix_ai_policies_agent_type'), table_name='ai_policies')
    op.drop_table('ai_policies')
    op.drop_index(op.f('ix_ai_agents_organization_id'), table_name='ai_agents')
    op.drop_index(op.f('ix_ai_agents_agent_type'), table_name='ai_agents')
    op.drop_table('ai_agents')
    # ### end Alembic commands ###
