"""add analytics_snapshots table

Revision ID: ed38e355962f
Revises: 4808a5de4384
Create Date: 2026-08-26 13:33:23.232017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed38e355962f'
down_revision: Union[str, None] = '4808a5de4384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_snapshots',
    sa.Column('organization_id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('store_id', sa.Uuid(native_uuid=False), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('cogs', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('price_changes_count', sa.Integer(), nullable=False),
    sa.Column('price_change_amount_sum', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('ai_recommendations_count', sa.Integer(), nullable=False),
    sa.Column('ai_approved_count', sa.Integer(), nullable=False),
    sa.Column('device_sync_attempts_count', sa.Integer(), nullable=False),
    sa.Column('device_sync_success_count', sa.Integer(), nullable=False),
    sa.Column('device_sync_failed_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(native_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_snapshots_organization_id'), 'analytics_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_snapshot_date'), 'analytics_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_analytics_snapshots_store_id'), 'analytics_snapshots', ['store_id'], unique=False)
    # Composite index for the actual query shape analytics_service always
    # uses (one org, one store-or-NULL grain, a date range) — the three
    # single-column indexes above exist because SQLAlchemy's index=True
    # emits them per-column, but this is the one the planner will pick.
    op.create_index(
        'ix_analytics_snapshots_org_store_date',
        'analytics_snapshots',
        ['organization_id', 'store_id', 'snapshot_date'],
        unique=False,
    )

    # Composite indexes so analytics_service's date-range aggregate queries
    # (grouped by day, filtered by organization_id) stay index-only scans
    # instead of full table scans as these tables grow — none of these
    # tables had a created_at/attempted_at index before Phase 15, since no
    # prior feature queried them by date range.
    op.create_index(
        'ix_price_history_org_created_at', 'price_history', ['organization_id', 'created_at'], unique=False
    )
    op.create_index(
        'ix_inventory_adjustments_org_type_created_at',
        'inventory_adjustments',
        ['organization_id', 'adjustment_type', 'created_at'],
        unique=False,
    )
    op.create_index(
        'ix_ai_pricing_recommendations_org_created_at',
        'ai_pricing_recommendations',
        ['organization_id', 'created_at'],
        unique=False,
    )
    op.create_index(
        'ix_device_sync_logs_attempted_at', 'device_sync_logs', ['attempted_at'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_sync_logs_attempted_at', table_name='device_sync_logs')
    op.drop_index('ix_ai_pricing_recommendations_org_created_at', table_name='ai_pricing_recommendations')
    op.drop_index('ix_inventory_adjustments_org_type_created_at', table_name='inventory_adjustments')
    op.drop_index('ix_price_history_org_created_at', table_name='price_history')
    op.drop_index('ix_analytics_snapshots_org_store_date', table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_store_id'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_snapshot_date'), table_name='analytics_snapshots')
    op.drop_index(op.f('ix_analytics_snapshots_organization_id'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    # ### end Alembic commands ###
